groups:
  - name: AppAlerts
    rules:
      - alert: WARNING-HighThroughput
        expr: rate(prod_eng_info_count_total[1m]) > 10
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: Increased info retrieval rate {{ $labels.value}} {{ $value }}
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: CRITICAL-HighThroughput
        expr: rate(prod_eng_info_count_total[1m]) > 50
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Increased info retrieval rate {{ $labels.value}} {{ $value }}
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
